### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by hjq5128** [homzer/MCC-KD#2]
Hello author, thank you for your contribution to the paper. When I was reproducing your code, I found some issues with the dataset. The error message is as follows. It seems that the index of the list is out of bounds. I checked your dataset instance on readme and it seems to be inconsistent with the dataset carried in your code at indices. We look forward to your reply

<torch.utils.data.dataloader. DataLoader object at 0x7f110bc46940> 
0%|                                                                                                                                                                   | 0/1120 [00:00<?, ?it/s] 
[rank0]: Traceback (most recent call last): 
[rank0]:    File "/home/flyvideo/Sata/lcc/MCC-KD/train_mcc.py", line 106, in <module> 
[rank0]:     fire.Fire(run) 
[rank0]:    File "/home/flyvideo/Sata2/anaconda3/envs/MCC_KD/lib/python3.8/site-packages/fire/core.py", line 141, in Fire 
[rank0]:      component_trace = _Fire(component, args, parsed_flag_args, context, name) 
[rank0]:    File "/home/flyvideo/Sata2/anaconda3/envs/MCC_KD/lib/python3.8/site-packages/fire/core.py", line 475, in _Fire 
[rank0]:     component, remaining_args = _CallAndUpdateTrace( 
[rank0]:    File "/home/flyvideo/Sata2/anaconda3/envs/MCC_KD/lib/python3.8/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace 
[rank0]:     component = fn(*varargs, **kwargs) 
[rank0]:    File "/home/flyvideo/Sata/lcc/MCC-KD/train_mcc.py", line 80, in run 
[rank0]:     for data in tqdm(dataloader): 
[rank0]:    File "/home/flyvideo/Sata2/anaconda3/envs/MCC_KD/lib/python3.8/site-packages/tqdm/std.py", line 1181, in __iter__ 
[rank0]:     for obj in iterable: 
[rank0]:    File "/home/flyvideo/Sata2/anaconda3/envs/MCC_KD/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 630, in __next__ 
[rank0]:     data = self._next_data() 
[rank0]:    File "/home/flyvideo/Sata2/anaconda3/envs/MCC_KD/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 673, in _next_data 
[rank0]:      data = self._dataset_fetcher.fetch(index)  # may raise StopIteration 
[rank0]:    File "/home/flyvideo/Sata2/anaconda3/envs/MCC_KD/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch 
[rank0]:      data = [self.dataset[idx] for idx in possibly_batched_index] 
[rank0]:    File "/home/flyvideo/Sata2/anaconda3/envs/MCC_KD/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp> 
[rank0]:      data = [self.dataset[idx] for idx in possibly_batched_index] 
[rank0]:    File "/home/flyvideo/Sata/lcc/MCC-KD/src/dataset.py", line 63, in __getitem__ 
[rank0]:     indices_a=data['indices'][id1], 
[rank0]: IndexError: list index out of range 
E1201 14:28:21.657156 140264516371648 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 834006) of binary: /home/flyvideo/Sata2/anaconda3/envs/MCC_KD/bin/python

**Comment by hjq5128** [comment]
this is the dataset carried in your code.

 "indices": [
            [
                [
                    134,
                    136
                ]
            ],
            [
                [
                    141,
                    143
                ]
            ],
            [
                [
                    141,
                    143
                ]
            ],
            [
                [
                    172,
                    174
                ]
            ],
            [
                [
                    143,
                    145
                ]
            ],
            [
                [
                    135,
                    137
                ]
            ],
            [
                [
                    144,
                    146
                ]
            ],
            [
                [
                    183,
                    185
                ]
            ]
        ]

**Comment by hjq5128** [comment]
this is the dataset in your readme.
"indices": [
        [
            23,
            28
        ],
        [
            42,
            47
        ]
    ]
